## dev | prod | test

#spring:
#  profiles:
#    active: @environment@

server:
  port: 6603

spring:
  profiles:
    active: dev
  application:
#  服务名称务必和git上配置文件名相对应
    name: @pom.artifactId@
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
